import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { Moon } from "lucide-react";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" className="">
      <body
        className={`
          h-screen max-h-screen overflow-y-hidden
          ${geistSans.variable} ${geistMono.variable} antialiased dark:bg-gray-900
        `}
      >
        <SidebarProvider>
          <AppSidebar />
          <main 
            className="
              h-screen w-full
              flex flex-col items-center justify-between
            ">
            <header
              className="
                flex w-full justify-between items-center
                py-2 px-2
              "
            >
              <SidebarTrigger className="h-auto w-auto p-2"/>
              <Button variant="ghost">
                <Moon className="size-5" />
              </Button>
            </header>
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}

export default RootLayout;