import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { Moon } from "lucide-react";
import { SidebarOpenIcon } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={`
          h-screen max-h-screen overflow-y-hidden
          flex flex-col items-center justify-between
          ${geistSans.variable} ${geistMono.variable} antialiased dark:bg-gray-900
        `}
      >
        <header
          className="
            flex w-full justify-between items-center
            py-2 px-2
          "
        >
          <div className="flex justify-center items-center">
            <Button variant="ghost">
              <SidebarOpenIcon className="size-5"/>
            </Button>
          </div>
          <Button variant="ghost">
            <Moon className="size-5" />
          </Button>
        </header>
        {children}
      </body>
    </html>
  );
}
